import { IonButton } from "@ionic/react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import NoSSRWrapper from "../components/NoSSRWrapper";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <NoSSRWrapper>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <IonButton>Click me</IonButton>
        </main>
      </div>
    </NoSSRWrapper>
  );
};

export default Home;
